{
  "name": "react-webpack5-template",
  "version": "1.0.0",
  "main": "index.js",
  "repository": "git@github.com:jgchenu/react-webpack5-template.git",
  "author": "jgchenu <jgchenu@foxmail.com>",
  "license": "MIT",
  "scripts": {
    "build": "cross-env NODE_ENV=production webpack",
    "dev": "cross-env NODE_ENV=development webpack serve",
    "eslint": "eslint --ext .js,.jsx,.ts,.tsx src --fix --max-warnings=0",
    "stylelint": "stylelint **/*.css, **/*.less",
    "lint": "yarn eslint  && yarn stylelint",
    "prepare": "husky install",
    "test": "jest"
  },
  "lint-staged": {
    "*.{js,ts,jsx,tsx}": [
      "eslint"
    ],
    "*.{css,less}": "stylelint"
  },
  "husky": {
    "hooks": {
      "commit-msg": "commitlint -E HUSKY_GIT_PARAMS",
      "pre-commit": "./pre_commit.sh && lint-staged"
    }
  },
  "devDependencies": {
    "@babel/core": "^7.18.9",
    "@babel/plugin-transform-runtime": "^7.18.9",
    "@babel/preset-env": "^7.18.9",
    "@babel/preset-react": "^7.18.6",
    "@babel/preset-typescript": "^7.18.6",
    "@babel/runtime-corejs3": "^7.18.9",
    "@commitlint/cli": "^17.0.3",
    "@commitlint/config-conventional": "^17.0.3",
    "@pmmmwh/react-refresh-webpack-plugin": "^0.5.7",
    "@svgr/webpack": "^6.3.0",
    "@testing-library/react": "^13.3.0",
    "@types/jest": "^28.1.6",
    "@types/react": "17.0.2",
    "@types/react-dom": "17.0.2",
    "@typescript-eslint/eslint-plugin": "^5.30.7",
    "@typescript-eslint/parser": "^5.30.7",
    "autoprefixer": "^10.4.7",
    "babel-loader": "^8.2.5",
    "clean-webpack-plugin": "^4.0.0",
    "cross-env": "^7.0.3",
    "css-loader": "^6.7.1",
    "css-minimizer-webpack-plugin": "^4.0.0",
    "eslint": "^8.20.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-config-standard": "^17.0.0",
    "eslint-plugin-import": "^2.26.0",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-prettier": "^4.2.1",
    "eslint-plugin-promise": "^6.0.0",
    "eslint-plugin-react": "^7.30.1",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-webpack-plugin": "^3.2.0",
    "html-webpack-plugin": "^5.5.0",
    "husky": "^8.0.1",
    "jest": "^28.1.3",
    "less": "^4.1.3",
    "less-loader": "^11.0.0",
    "lint-staged": "^13.0.3",
    "mini-css-extract-plugin": "^2.6.1",
    "postcss": "^8.4.14",
    "postcss-less": "^6.0.0",
    "postcss-loader": "^7.0.1",
    "prettier": "^2.7.1",
    "progress-bar-webpack-plugin": "^2.1.0",
    "react-refresh": "^0.14.0",
    "style-loader": "^3.3.1",
    "stylelint": "^14.9.1",
    "stylelint-config-css-modules": "^4.1.0",
    "stylelint-config-idiomatic-order": "^8.1.0",
    "stylelint-config-prettier": "^9.0.3",
    "stylelint-config-recommended": "^8.0.0",
    "stylelint-config-standard": "^26.0.0",
    "stylelint-webpack-plugin": "^3.3.0",
    "ts-jest": "^28.0.7",
    "ts-loader": "^9.3.1",
    "tsconfig-paths-webpack-plugin": "^3.5.2",
    "typescript": "^4.7.4",
    "typescript-plugin-css-modules": "^3.4.0",
    "webpack": "^5.73.0",
    "webpack-cli": "^4.10.0",
    "webpack-dev-server": "^4.9.3"
  },
  "dependencies": {
    "@reduxjs/toolkit": "^1.8.3",
    "classnames": "^2.3.1",
    "normalize.css": "^8.0.1",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-redux": "^8.0.2",
    "react-router-dom": "^6.3.0",
    "redux": "^4.2.0"
  }
}
